[nodes]
UCLA: _ network=/world router=/UCLA.Router/ position=-23.7,-27.3,0
SAVI: _ network=/world router=/SAVI.Router/ position=-15.9,-34.9,0
TNO: _ network=/world router=/TNO.Router/ position=0.7,-42,0
MEMPHIS: _ network=/world router=/MEMPHIS.Router/ position=-17.9,-27.9,0
URJC: _ network=/world router=/URJC.Router/ position=-0.4,-32,0
WASEDA: _ network=/world router=/WASEDA.Router/ position=28.2,-28.7,0
UFBA: _ network=/world router=/UFBA.Router/ position=-9.9,2.9,0
MML2: _ network=/world router=/MML2.Router/ position=4.5,-30.6,0
MML1: _ network=/world router=/MML1.Router/ position=6.4,-28.1,0
ARIZONA: _ network=/world router=/ARIZONA.Router/ position=-22.1,-25.6,0
SINGAPORE: _ network=/world router=/SINGAPORE.Router/ position=20.7,-1,0
FRANKFURT: _ network=/world router=/FRANKFURT.Router/ position=2.1,-40.1,0
SRRU: _ network=/world router=/SRRU.Router/ position=20.7,-12.2,0
DELFT: _ network=/world router=/DELFT.Router/ position=1,-38.1,0
WU: _ network=/world router=/WU.Router/ position=-18,-30.9,0
MINHO: _ network=/world router=/MINHO.Router/ position=-1.7,-33.8,0
[switches]
[links]
UCLA:FRANKFURT delay=150ms
UCLA:URJC delay=155ms
UCLA:MML1 delay=195ms
UCLA:ARIZONA delay=13ms
UCLA:WU delay=60ms
UCLA:UFBA delay=159ms
UCLA:WASEDA delay=109ms
SAVI:MEMPHIS delay=52ms
TNO:DELFT delay=3ms
TNO:MML2 delay=59ms
MEMPHIS:ARIZONA delay=59ms
MEMPHIS:WU delay=106ms
MEMPHIS:DELFT delay=125ms
URJC:FRANKFURT delay=37ms
URJC:MML1 delay=60ms
URJC:MINHO delay=27ms
WASEDA:SINGAPORE delay=87ms
UFBA:WU delay=218ms
UFBA:MML2 delay=187ms
MML2:MML1 delay=3ms
MML1:FRANKFURT delay=49ms
ARIZONA:WU delay=49ms
SINGAPORE:FRANKFURT delay=163ms
SINGAPORE:SRRU delay=37ms
FRANKFURT:DELFT delay=8ms
